const skills = [
  { technology: 'javascript', category: 'languages', familiarity: 'high' },
  { technology: 'typescript', category: 'languages', familiarity: 'high' },
  { technology: 'python', category: 'languages', familiarity: 'high' },
  { technology: 'bash', category: 'languages', familiarity: 'high' },
  { technology: 'sql', category: 'languages', familiarity: 'high' },
  { technology: 'mongodb', category: 'languages', familiarity: 'high' },
  { technology: 'html', category: 'languages', familiarity: 'high' },
  { technology: 'css', category: 'languages', familiarity: 'high' },
  { technology: 'graphql', category: 'languages', familiarity: 'low' },
  { technology: 'csharp', category: 'languages', familiarity: 'low' },
  { technology: 'java', category: 'languages', familiarity: 'low' },
  { technology: 'ruby', category: 'languages', familiarity: 'low' },
  { technology: 'racket', category: 'languages', familiarity: 'low' },
  { technology: 'visualbasic', category: 'languages', familiarity: 'low' },
  { technology: 'matlab', category: 'languages', familiarity: 'low' },
  { technology: 'nodejs', category: 'frameworks', familiarity: 'high' },
  { technology: 'express', category: 'frameworks', familiarity: 'high' },
  { technology: 'react', category: 'frameworks', familiarity: 'high' },
  { technology: 'jest', category: 'frameworks', familiarity: 'high' },
  { technology: 'postgresql', category: 'frameworks', familiarity: 'high' },
  { technology: 'mongoose', category: 'frameworks', familiarity: 'high' },
  { technology: 'apollo', category: 'frameworks', familiarity: 'low' },
  { technology: 'cypress', category: 'frameworks', familiarity: 'low' },
  { technology: 'materialui', category: 'frameworks', familiarity: 'low' },
  { technology: 'bootstrap', category: 'frameworks', familiarity: 'low' },
  { technology: 'git', category: 'tools', familiarity: 'high' },
  { technology: 'github', category: 'tools', familiarity: 'high' },
  { technology: 'postman', category: 'tools', familiarity: 'high' },
  { technology: 'vscode', category: 'tools', familiarity: 'high' },
  { technology: 'redux', category: 'tools', familiarity: 'high' },
  { technology: 'axios', category: 'tools', familiarity: 'high' },
  { technology: 'reactrouter', category: 'tools', familiarity: 'high' },
  // { technology: 'kubuntu', category: 'tools', familiarity: 'high' },
  // { technology: 'npm', category: 'tools', familiarity: 'high' },
  // { technology: 'ubuntu', category: 'tools', familiarity: 'high' },
  // { technology: 'windows', category: 'tools', familiarity: 'high' },
  { technology: 'docker', category: 'tools', familiarity: 'low' },
  { technology: 'githubactions', category: 'tools', familiarity: 'low' },
  { technology: 'eslint', category: 'tools', familiarity: 'low' },
  { technology: 'jwt', category: 'tools', familiarity: 'low' },
  { technology: 'passportjs', category: 'tools', familiarity: 'lows' },
  { technology: 'webpack', category: 'tools', familiarity: 'low' },
  { technology: 'vite', category: 'tools', familiarity: 'low' },
  // { technology: 'tanstackquery', category: 'tools', familiarity: 'low' },
  // { technology: 'linux', category: 'tools', familiarity: 'low' },
  // { technology: 'lodash', category: 'tools', familiarity: 'low' },
];

export default skills;
